import pandas as pd

product_categories = {
    # =========================================================================
    # Beauty & Fashion
    # =========================================================================
    "10ml Perfume Alcohol Spray Bottle - Black": "Beauty & Fashion",
    "10ml Perfume Alcohol Spray Bottle - Blue": "Beauty & Fashion",
    "10ml Perfume Alcohol Spray Bottle - Gray": "Beauty & Fashion",
    "10ml Perfume Alcohol Spray Bottle - Pink": "Beauty & Fashion",
    "10ml Perfume Alcohol Spray Bottle - Purple": "Beauty & Fashion",
    "10ml Perfume Alcohol Spray Bottle - Transparent": "Beauty & Fashion",
    "10ml Perfume Alcohol Spray Bottle - White": "Beauty & Fashion",
    "Anello Bag - Mix": "Beauty & Fashion",
    "Anello Bag - Pink": "Beauty & Fashion",
    "Anello Bag - Red": "Beauty & Fashion",
    "Apple Watch Strap - Knitted Design 1 - Cowboy 42mm": "Beauty & Fashion",
    "Apple Watch Strap - Knitted Design 1 - Cowboy 44mm": "Beauty & Fashion",
    "Apple Watch Strap - Knitted Design 1 - Rainbow 42mm": "Beauty & Fashion",
    "Apple Watch Strap - Knitted Design 1 - Rainbow 44mm": "Beauty & Fashion",
    "Apple Watch Strap - Leather Design 1 - Black 42mm": "Beauty & Fashion",
    "Apple Watch Strap - Leather Design 1 - Black 44mm": "Beauty & Fashion",
    "Apple Watch Strap - Leather Design 1 - Gray 44mm": "Beauty & Fashion",
    "Apple Watch Strap - Leather Design 1 - White 42mm": "Beauty & Fashion",
    "Apple Watch Strap - Leather Design 1 - White 44mm": "Beauty & Fashion",
    "Canvas Bag - Shiba Inu - Black": "Beauty & Fashion",
    "Canvas Bag - Shiba Inu - White": "Beauty & Fashion",
    "Canvas Bag - Shiba Inu - Yellow": "Beauty & Fashion",
    "Children's Sun Visor - Plain Black": "Beauty & Fashion",
    "Children's Sun Visor - Plain Cream": "Beauty & Fashion",
    "Children's Sun Visor - Plain Gray": "Beauty & Fashion",
    "Children's Visor - Plain Black": "Beauty & Fashion",
    "Children's Visor - Plain Cream": "Beauty & Fashion",
    "Children's Visor - Plain Gray": "Beauty & Fashion",
    "Diniwell Makeup Pouch - Black Black": "Beauty & Fashion",
    "Diniwell Makeup Pouch - Black Red": "Beauty & Fashion",
    "Diniwell Makeup Pouch - Gray": "Beauty & Fashion",
    "Diniwell Makeup Pouch - Green": "Beauty & Fashion",
    "Diniwell Makeup Pouch - Navy": "Beauty & Fashion",
    "Diniwell Makeup Pouch - Pink": "Beauty & Fashion",
    "Disposable Compressed Towel - Body Brand A (mengzhiling)": "Beauty & Fashion",
    "Disposable Compressed Towel - Body Brand B (langqi)": "Beauty & Fashion",
    "Disposable Compressed Towel - Body Brand C (minaier)": "Beauty & Fashion",
    "Disposable Compressed Towel - Face Brand A (yifuyan)": "Beauty & Fashion",
    "Disposable Compressed Towel - Face Brand A (yifuyan) 20x20": "Beauty & Fashion",
    "Disposable Compressed Towel - Face Brand A (yifuyan) 24x30": "Beauty & Fashion",
    "Flat Nailcutter Keychain": "Beauty & Fashion",
    "Issey Miyake-like Make up Pouch - Black": "Beauty & Fashion",
    "Issey Miyake-like Make up Pouch - Cream": "Beauty & Fashion",
    "Issey Miyake-like Make up Pouch - Pink": "Beauty & Fashion",
    "Issey Miyake-like Make up Pouch - Silver": "Beauty & Fashion",
    "Lightweight Freesize Sun Protection Jacket - Gray": "Beauty & Fashion",
    "Lightweight Freesize Sun Protection Jacket - Pink": "Beauty & Fashion",
    "Lightweight Freesize Sun Protection Jacket - Sky Blue": "Beauty & Fashion",
    "Lightweight Freesize Sun Protection Jacket - White": "Beauty & Fashion",
    "Lipstick/Brush Organizer - Large Pink": "Beauty & Fashion",
    "Lipstick/Brush Organizer - Large Red": "Beauty & Fashion",
    "Lipstick/Brush Organizer - Medium Gray": "Beauty & Fashion",
    "Lipstick/Brush Organizer - Medium Pink": "Beauty & Fashion",
    "Lipstick/Brush Organizer - Medium Red": "Beauty & Fashion",
    "Lipstick/Brush Organizer - Small Gray": "Beauty & Fashion",
    "Lipstick/Brush Organizer - Small Mint": "Beauty & Fashion",
    "Lipstick/Brush Organizer - Small Pink": "Beauty & Fashion",
    "Lipstick/Brush Organizer - Small Red": "Beauty & Fashion",
    "Makeup Cushion Puff - 5pcs Round with Hard Case": "Beauty & Fashion",
    "Makeup Cushion Puff - 5pcs Triangle with Hard Case": "Beauty & Fashion",
    "Makeup Cushion Puff - Diamond": "Beauty & Fashion",
    "Makeup Cushion Puff - Round": "Beauty & Fashion",
    "Makeup Cushion Puff - Round with Hard Case": "Beauty & Fashion",
    "Makeup Cushion Puff - Square": "Beauty & Fashion",
    "Makeup Cushion Puff - Square with Hard Case": "Beauty & Fashion",
    "Makeup Cushion Puff - Triangle": "Beauty & Fashion",
    "Makeup Cushion Puff - Triangle with Hard Case": "Beauty & Fashion",
    "Refillable Vacuum Eye Cream Bottle - 10ml": "Beauty & Fashion",
    "Refillable Vacuum Eye Cream Bottle - 15ml": "Beauty & Fashion",
    "Refillable Vacuum Eye Cream Bottle - 5ml": "Beauty & Fashion",
    "Roll up Compact Shopping Bag (Nautiloop) - Black": "Beauty & Fashion",
    "Roll up Compact Shopping Bag (Nautiloop) - Blue": "Beauty & Fashion",
    "Roll up Compact Shopping Bag (Nautiloop) - Orange": "Beauty & Fashion",
    "Roll up Compact Shopping Bag (Nautiloop) - Pink": "Beauty & Fashion",
    "Roll up Compact Shopping Bag (Nautiloop) - Red": "Beauty & Fashion",
    "Sling Bag Sneaker Shape - Black": "Beauty & Fashion",
    "Sling Bag Sneaker Shape - Navy Blue": "Beauty & Fashion",
    "Sling Bag Sneaker Shape - Red": "Beauty & Fashion",
    "Sling Bag Sneaker Shape - Yellow": "Beauty & Fashion",
    "Spatter-proof Nailcutter Set (Set of 4) - Dark Green": "Beauty & Fashion",
    "Spatter-proof Nailcutter Set (Set of 4) - Set of 6 - Dark Green": "Beauty & Fashion",
    "Uniqlo-like Body Bag - Beige": "Beauty & Fashion",
    "Uniqlo-like Body Bag - Black": "Beauty & Fashion",
    "Uniqlo-like Body Bag - Blue": "Beauty & Fashion",
    "Uniqlo-like Body Bag - Gray": "Beauty & Fashion",
    "Uniqlo-like Body Bag - Pink": "Beauty & Fashion",
    "Uniqlo-like Body Bag Supplier 2  - Beige": "Beauty & Fashion",
    "Uniqlo-like Body Bag Supplier 2  - Black": "Beauty & Fashion",
    "Uniqlo-like Body Bag Supplier 2  - Gray": "Beauty & Fashion",
    "Uniqlo-like Body Bag Supplier 2  - Green": "Beauty & Fashion",
    "Uniqlo-like Body Bag Supplier 2  - Orange": "Beauty & Fashion",
    "Xiaomi Backpack - Gray": "Beauty & Fashion",

    # =========================================================================
    # Travel
    # =========================================================================
    "8-in-1 Travel Bottle Set - Stupid Little Elephant - Blue": "Travel",
    "8-in-1 Travel Bottle Set - Stupid Little Elephant - Gray": "Travel",
    "8-in-1 Travel Bottle Set - Stupid Little Elephant - Pink": "Travel",
    "Inflatable Travel Neck Pillow  - Black": "Travel",
    "Inflatable Travel Neck Pillow  - Gray": "Travel",
    "Inflatable Travel Neck Pillow  - Green": "Travel",
    "Inflatable Travel Neck Pillow  - Navy": "Travel",
    "Inflatable Travel Neck Pillow  - Pink": "Travel",
    "Multi-function Passport Holder Wallet with Simcard Slot - Black": "Travel",
    "Multi-function Passport Holder Wallet with Simcard Slot - Brown": "Travel",
    "Multi-function Passport Holder Wallet with Simcard Slot - Navy": "Travel",
    "Multifunctional Travel Adapter - Black": "Travel",
    "Multifunctional Travel Adapter - White": "Travel",
    "PU Leather Multi-function Passport Holder - Black": "Travel",
    "PU Leather Multi-function Passport Holder - Blue": "Travel",
    "PU Leather Multi-function Passport Holder - Gold": "Travel",
    "PU Leather Multi-function Passport Holder - Red": "Travel",
    "PU Leather Multi-function Passport Holder - Silver": "Travel",
    "PU Leather Mutli-function Passport Holder - Gold": "Travel",
    "PU Leather Passport Holder - Black": "Travel",
    "PU Leather Passport Holder - Brown": "Travel",
    "PU Leather Passport Holder - Dark Brown": "Travel",
    "PU Leather Passport Holder - Lime Green": "Travel",
    "PU Leather Passport Holder - Pink": "Travel",
    "PU Leather Passport Holder with Sim Card Holder - Black": "Travel",
    "PU Leather Passport Holder with Sim Card Holder - Brown": "Travel",
    "PU Leather Passport Holder with Sim Card Holder - Dark Brown": "Travel",
    "PU Leather Passport Holder with Sim Card Holder - Gray": "Travel",
    "PU Leather Passport Holder with Sim Card Holder - Navy": "Travel",
    "PU Leather Plain Buckle Passport Holder - Black": "Travel",
    "PU Leather Plain Buckle Passport Holder - Dark Brown": "Travel",
    "PU Leather Plain Buckle Passport Holder - Red": "Travel",
    "Portable Hanging Digital Weighing Scale - Black": "Travel",
    "Portable Hanging Digital Weighing Scale - Silver": "Travel",
    "Set Travel Luggage Organizer - Set of 6 - Black": "Travel",
    "Set Travel Luggage Organizer - Set of 6 - Gray": "Travel",
    "Set Travel Luggage Organizer - Set of 6 - Navy": "Travel",
    "Set Travel Luggage Organizer - Set of 6 - Wine": "Travel",
    "Set Travel Luggage Organizer - Set of 7 - Beige": "Travel",
    "Set Travel Luggage Organizer - Set of 7 - Black": "Travel",
    "Set Travel Luggage Organizer - Set of 7 - Gray": "Travel",
    "Set Travel Luggage Organizer - Set of 7 - Navy": "Travel",
    "Set Travel Luggage Organizer - Set of 7 - Pink": "Travel",
    "Set Travel Luggage Organizer Style 2 - Set of 7 - Green": "Travel",
    "Set Travel Luggage Organizer Style 2 - Set of 7 - Orange": "Travel",
    "Set Travel Luggage Organizer Style 2 - Set of 7 - Pink": "Travel",
    "Set Travel Luggage Organizer Style 2 - Set of 7 - Wine": "Travel",
    "Transparent Shoe Bag - Apple Green": "Travel",
    "Transparent Shoe Bag - Black": "Travel",
    "Transparent Shoe Bag - Fuschia": "Travel",
    "Transparent Shoe Bag - Sky Blue": "Travel",
    "Travel Liquid Dispenser Pods (Set of 4) - Neutral": "Travel",
    "Travel Tech Organizer Customizable - Black": "Travel",
    "Travel Tech Organizer Customizable - Gray": "Travel",
    "Travel Tech Organizer Customizable - Navy": "Travel",
    "Travel Tech Organizer Customizable - Purple": "Travel",
    "Travel Tech Organizer Customizable - Red": "Travel",
    "Travel Tech Organizer Customizable - Sky Blue": "Travel",
    "Vacuum Bags Design Set 1 - Hand Pump": "Travel",
    "Vacuum Bags Design Set 1 - Pink Elephant 60x80cm": "Travel",
    "Vacuum Bags Design Set 1 - Pink Elephant 80x100cm": "Travel",
    "Vacuum Bags Design Set 1 - Yellow Lemon 50x70cm": "Travel",
    "Vacuum Bags Design Set 1 - Yellow Lemon 60x80cm": "Travel",
    "Vacuum Bags Design Set 1 - Yellow Lemon 70x100cm": "Travel",
    "Vacuum Bags Design Set 1 - Yellow Lemon 80x100cm": "Travel",
    "Vacuum Bags Handroll - Sea 35x50cm": "Travel",
    "Vacuum Bags Transparent - 50x70cm": "Travel",
    "Vacuum Bags Transparent - 60x80cm": "Travel",
    "Vacuum Bags Transparent - 70x100cm": "Travel",
    "Vacuum Bags Transparent - Hand Pump": "Travel",

    # =========================================================================
    # Organizers
    # =========================================================================
    "Bathroom Umbrella Hook Organizer - Blue": "Organizers",
    "Bathroom Umbrella Hook Organizer - Green": "Organizers",
    "Bathroom Umbrella Hook Organizer - Pink": "Organizers",
    "Collapsible Box Organizer - Medium Ivory": "Organizers",
    "Desk Organizer Shelf System - Black": "Organizers",
    "Desk Organizer Shelf System - White": "Organizers",
    "Desk Organizer Shelf System - Wood": "Organizers",
    "Fabric Foldable Rectangle Organizer - Black White Checkered": "Organizers",
    "Fabric Foldable Rectangle Organizer - Blue Polar Bears": "Organizers",
    "Fabric Foldable Rectangle Organizer - Gray White Checkered": "Organizers",
    "Fabric Foldable Rectangle Organizer - Gray White Chevron": "Organizers",
    "Fabric Foldable Rectangle Organizer - Green White Chevron": "Organizers",
    "Fabric Foldable Rectangle Organizer - Pink Checkered": "Organizers",
    "Fabric Foldable Rectangle Organizer - Pink Polar Bears": "Organizers",
    "Fabric Foldable Rectangle Organizer - White Black Checkered": "Organizers",
    "Fabric Foldable Rectangle Organizer - White Trees": "Organizers",
    "Fabric Foldable Rectangle Organizer - White Whales": "Organizers",
    "Fabric Foldable Rectangle Organizer - Yellow White Diamond": "Organizers",
    "Felt Foldable Organizer - Large Beige": "Organizers",
    "Felt Foldable Organizer - Large Black": "Organizers",
    "Felt Foldable Organizer - Large Khaki": "Organizers",
    "Felt Foldable Organizer - Medium Beige": "Organizers",
    "Felt Foldable Organizer - Medium Black": "Organizers",
    "Felt Foldable Organizer - Medium Khaki": "Organizers",
    "Felt Insert Bag with Multi Pockets - Beige Large (28*25*17cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Beige Medium (26*20*13cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Beige Small (21*17*13cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Black Large (28*25*17cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Black Medium (26*20*13cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Black Small (21*17*13cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Navy Large (28*25*17cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Navy Medium (26*20*13cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Navy Small (21*17*13cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Pink Large (28*25*17cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Pink Medium (26*20*13cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Pink Small (21*17*13cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Random Large (28*25*17cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Random Medium (26*20*13cm)": "Organizers",
    "Felt Insert Bag with Multi Pockets - Random Small (21*17*13cm)": "Organizers",
    "Foldable File Organizer - Large Apricot": "Organizers",
    "Foldable File Organizer - Large Apricot No OPP": "Organizers",
    "Foldable File Organizer - Large Black": "Organizers",
    "Foldable File Organizer - Large Black No OPP": "Organizers",
    "Foldable File Organizer - Large Blue": "Organizers",
    "Foldable File Organizer - Large Light Gray": "Organizers",
    "Foldable File Organizer - Large Light Gray No OPP": "Organizers",
    "Foldable File Organizer - Large Pink": "Organizers",
    "Foldable File Organizer - Large Transparent": "Organizers",
    "Foldable File Organizer - Large Transparent No OPP": "Organizers",
    "Foldable File Organizer - Large White": "Organizers",
    "Foldable File Organizer - Large White No OPP": "Organizers",
    "Front Pocket Toiletry Organizer - Black": "Organizers",
    "Front Pocket Toiletry Organizer - Brown": "Organizers",
    "Front Pocket Toiletry Organizer - Gray": "Organizers",
    "Front Pocket Toiletry Organizer - Navy": "Organizers",
    "Front Pocket Toiletry Organizer - Pink": "Organizers",
    "Laundry Hamper - Large Aircraft": "Organizers",
    "Laundry Hamper - Large Balloon Children": "Organizers",
    "Laundry Hamper - Large Black Game Console": "Organizers",
    "Laundry Hamper - Large Blue Dinosaur": "Organizers",
    "Laundry Hamper - Large Blue White Triangles": "Organizers",
    "Laundry Hamper - Large Cat": "Organizers",
    "Laundry Hamper - Large Chick": "Organizers",
    "Laundry Hamper - Large Construction Vehicles": "Organizers",
    "Laundry Hamper - Large Dark Blue Varying Dinosaurs": "Organizers",
    "Laundry Hamper - Large Denim Laundry": "Organizers",
    "Laundry Hamper - Large Dinosaur": "Organizers",
    "Laundry Hamper - Large Drawstring Animal Graffiti": "Organizers",
    "Laundry Hamper - Large Drawstring Blue White Triangles": "Organizers",
    "Laundry Hamper - Large Drawstring Forest": "Organizers",
    "Laundry Hamper - Large Drawstring Rocking Horse": "Organizers",
    "Laundry Hamper - Large Duck": "Organizers",
    "Laundry Hamper - Large Elephant": "Organizers",
    "Laundry Hamper - Large Elk Pine": "Organizers",
    "Laundry Hamper - Large Excavator": "Organizers",
    "Laundry Hamper - Large Forest Animals": "Organizers",
    "Laundry Hamper - Large Fox": "Organizers",
    "Laundry Hamper - Large Hippo": "Organizers",
    "Laundry Hamper - Large Hippo Balloon": "Organizers",
    "Laundry Hamper - Large Lion": "Organizers",
    "Laundry Hamper - Large Lion Crown": "Organizers",
    "Laundry Hamper - Large Lion Father": "Organizers",
    "Laundry Hamper - Large Owl": "Organizers",
    "Laundry Hamper - Large Penguin": "Organizers",
    "Laundry Hamper - Large Pineapple": "Organizers",
    "Laundry Hamper - Large Pink Dinosaur": "Organizers",
    "Laundry Hamper - Large Rabbit": "Organizers",
    "Laundry Hamper - Large Sports Balls": "Organizers",
    "Laundry Hamper - Medium Aircraft": "Organizers",
    "Laundry Hamper - Medium Colorful Graffiti": "Organizers",
    "Laundry Hamper - Medium Construction Vehicles": "Organizers",
    "Laundry Hamper - Medium Dark Blue Varying Dinosaurs": "Organizers",
    "Laundry Hamper - Medium Excavator": "Organizers",
    "Laundry Hamper - Medium Flora": "Organizers",
    "Laundry Hamper - Medium Gray Bunny": "Organizers",
    "Laundry Hamper - Medium Green Cloud Bear": "Organizers",
    "Laundry Hamper - Medium Green Fish": "Organizers",
    "Laundry Hamper - Medium Navy Cats": "Organizers",
    "Laundry Hamper - Medium Pine Tree": "Organizers",
    "Laundry Hamper - Medium Pink Fox Hello": "Organizers",
    "Laundry Hamper - Medium Red Strawberry": "Organizers",
    "Laundry Hamper - Medium Sports Balls": "Organizers",
    "Laundry Hamper - Medium Washday": "Organizers",
    "Laundry Hamper - Small Cats": "Organizers",
    "Laundry Hamper - Small Dinosaurs": "Organizers",
    "Laundry Hamper - XS Black White Stripes": "Organizers",
    "Laundry Hamper - XS Polka Dots": "Organizers",
    "Metal Key Holder - Black": "Organizers",
    "Metal Key Holder - Blue": "Organizers",
    "Metal Key Holder - Green": "Organizers",
    "Metal Key Holder - Orange": "Organizers",
    "Metal Key Holder - Silver": "Organizers",
    "Metal Key Holder - Yellow": "Organizers",
    "Metal Key Holder with Hook - Black": "Organizers",
    "Metal Key Holder with Hook - Black - Plain Packaging": "Organizers",
    "Metal Key Holder with Hook - Black Honeycomb": "Organizers",
    "Metal Key Holder with Hook - Black Honeycomb - Plain Packaging": "Organizers",
    "Metal Key Holder with Hook - Blue": "Organizers",
    "Metal Key Holder with Hook - Gray": "Organizers",
    "Metal Key Holder with Hook - Gray - Plain Packaging": "Organizers",
    "Metal Key Holder with Hook - Green": "Organizers",
    "Metal Key Holder with Hook - Green - Plain Packaging": "Organizers",
    "Metal Key Holder with Hook - Navy": "Organizers",
    "Metal Key Holder with Hook - Navy - Plain Packaging": "Organizers",
    "Metal Key Holder with Hook - Plain Cream": "Organizers",
    "Metal Key Holder with Hook - Purple": "Organizers",
    "Metal Key Holder with Hook - Purple - Plain Packaging": "Organizers",
    "Multi Compartment Pouch Toiletry Organizer - Black": "Organizers",
    "Multi Compartment Pouch Toiletry Organizer - Gray": "Organizers",
    "Multi Compartment Pouch Toiletry Organizer - Navy": "Organizers",
    "Pill Shaped Medicine Storage with Pill Cutter - Gray": "Organizers",
    "Pill Shaped Medicine Storage with Pill Cutter - White": "Organizers",
    "Pill Shaped Medicine Storage with Pill Cutter - Yellow": "Organizers",
    "Plastic Basket Organizer Rattan - Cream": "Organizers",
    "Plastic Basket Organizer Rattan - Dark Brown": "Organizers",
    "Plastic Basket Organizer Rattan - Light Brown": "Organizers",
    "Plastic Bird Like Hanger Organizer - White/Orange": "Organizers",
    "Portable Medicine Box Drawer Type - Blue": "Organizers",
    "Portable Medicine Box Drawer Type - Gray": "Organizers",
    "Portable Medicine Box Drawer Type - Green": "Organizers",
    "Portable Medicine Box Drawer Type - Pink": "Organizers",
    "Portable Medicine Box with Pill Cutter - Blue": "Organizers",
    "Portable Medicine Box with Pill Cutter - Green": "Organizers",
    "Portable Medicine Box with Pill Cutter - White": "Organizers",
    "Portable Medicine Box with Pill Cutter - White/Gray": "Organizers",
    "Portable Medicine Box with Pill Cutter - White/Pink": "Organizers",
    "Portable Medicine Box with Pill Cutter - White/Yellow": "Organizers",
    "Pouch Toiletry Organizer - Black": "Organizers",
    "Pouch Toiletry Organizer - Blue": "Organizers",
    "Pouch Toiletry Organizer - Brown": "Organizers",
    "Pouch Toiletry Organizer - Gray": "Organizers",
    "Pouch Toiletry Organizer - Red": "Organizers",
    "Shower Storage - Box White": "Organizers",
    "Square Toiletry Organizer - Black": "Organizers",
    "Square Toiletry Organizer - Gray": "Organizers",
    "Square Toiletry Organizer - Navy": "Organizers",
    "Square Toiletry Organizer - Purple": "Organizers",
    "Square Toiletry Organizer - Red": "Organizers",
    "Square Toiletry Organizer - Sky Blue": "Organizers",
    "TRAVEL Light Weight Square Toiletry Organizer - Beige": "Organizers",
    "TRAVEL Light Weight Square Toiletry Organizer - Navy": "Organizers",
    "TRAVEL Light Weight Square Toiletry Organizer - Pink": "Organizers",
    "Travel Toiletry Organizer - Black": "Organizers",
    "Travel Toiletry Organizer - Gray": "Organizers",
    "Travel Toiletry Organizer - Navy": "Organizers",
    "Travel Toiletry Organizer - Purple": "Organizers",
    "Travel Toiletry Organizer - Rose Pink": "Organizers",
    "Travel Toiletry Organizer - Sky Blue": "Organizers",
    "Travel Toiletry Organizer - Wine": "Organizers",
    "Travel Toiletry Organizer with Flap - Gray": "Organizers",
    "Travel Toiletry Organizer with Flap - Navy": "Organizers",
    "Tube Toiletry Organizer - Black": "Organizers",
    "Tube Toiletry Organizer - Blue": "Organizers",
    "Tube Toiletry Organizer - Dark Blue": "Organizers",
    "Tube Toiletry Organizer - Dark Gray": "Organizers",
    "Tube Toiletry Organizer - Light Gray": "Organizers",
    "Tube Toiletry Organizer - Purple": "Organizers",
    "Tube Toiletry Organizer - Sky Blue": "Organizers",
    "XUNGLBAG Thick Square Toiletry Organizer - Gray": "Organizers",
    "XUNGLBAG Thick Square Toiletry Organizer - Navy": "Organizers",

    # =========================================================================
    # Electronics
    # =========================================================================
    "Bluetooth Earphones Airpod-like - Gen 3 - White": "Electronics",
    "Bluetooth Earphones Airpod-like - Pro Gen 2 - White": "Electronics",
    "Bluetooth Earphones Airpod-like - Pro Gen 3 - White": "Electronics",
    "Keyboard Cleaner 7-in-1 - Black": "Electronics",
    "Keyboard Cleaner 7-in-1 - White": "Electronics",
    "Metal Rotatable Cellphone/Tablet Stand - Black": "Electronics",
    "Metal Rotatable Cellphone/Tablet Stand - White": "Electronics",
    "Motion Sensor LED - Cool Light": "Electronics",
    "Motion Sensor LED - Cool Light with On/Off Switch": "Electronics",
    "Motion Sensor LED - Dual Tone with On/Off Switch": "Electronics",
    "Motion Sensor LED - Warm Light": "Electronics",
    "Motion Sensor LED - Warm Light with On/Off Switch": "Electronics",
    "Portable Rechargeable Desk Fan - 10.8 - White": "Electronics",
    "Portable Rechargeable Desk Fan - 15.5 - Dark Blue": "Electronics",
    "Portable Rechargeable Handheld Fan - Green": "Electronics",
    "Portable Rechargeable Handheld Fan - Orange": "Electronics",
    "Portable Rechargeable Handheld Fan - White": "Electronics",
    "Wire Protector - Badz Maru": "Electronics",
    "Wire Protector - Batman Logo": "Electronics",
    "Wire Protector - Batman Round Face": "Electronics",
    "Wire Protector - Buzz Lightyear": "Electronics",
    "Wire Protector - Captain America Logo": "Electronics",
    "Wire Protector - Cardcaptor": "Electronics",
    "Wire Protector - Charmander": "Electronics",
    "Wire Protector - Chip": "Electronics",
    "Wire Protector - Coke": "Electronics",
    "Wire Protector - Cookie Monster": "Electronics",
    "Wire Protector - Daisy": "Electronics",
    "Wire Protector - Daisy Bottom": "Electronics",
    "Wire Protector - Dale": "Electronics",
    "Wire Protector - Donald": "Electronics",
    "Wire Protector - Donald Bottom": "Electronics",
    "Wire Protector - Doraemon": "Electronics",
    "Wire Protector - Eevee": "Electronics",
    "Wire Protector - Eeyore": "Electronics",
    "Wire Protector - Elmo": "Electronics",
    "Wire Protector - Gingerbread Man": "Electronics",
    "Wire Protector - Godzilla": "Electronics",
    "Wire Protector - Hello Kitty": "Electronics",
    "Wire Protector - Ironman Head": "Electronics",
    "Wire Protector - Ironman Round Face": "Electronics",
    "Wire Protector - Little Green Men": "Electronics",
    "Wire Protector - Mario": "Electronics",
    "Wire Protector - Mickey Bottom": "Electronics",
    "Wire Protector - Mickey Mouse": "Electronics",
    "Wire Protector - Mike Wazowski": "Electronics",
    "Wire Protector - Milk Tea": "Electronics",
    "Wire Protector - Minion One eye": "Electronics",
    "Wire Protector - Minion Two eyes": "Electronics",
    "Wire Protector - Minnie Bottom": "Electronics",
    "Wire Protector - Minnie Mouse": "Electronics",
    "Wire Protector - My Melody": "Electronics",
    "Wire Protector - No Face": "Electronics",
    "Wire Protector - Pepsi": "Electronics",
    "Wire Protector - Piglet": "Electronics",
    "Wire Protector - Pikachu Body": "Electronics",
    "Wire Protector - Pikachu Head": "Electronics",
    "Wire Protector - Pluto": "Electronics",
    "Wire Protector - Pooh": "Electronics",
    "Wire Protector - Pooh Bottom": "Electronics",
    "Wire Protector - Rilakuma": "Electronics",
    "Wire Protector - Sailor Moon": "Electronics",
    "Wire Protector - Sakura Momoko": "Electronics",
    "Wire Protector - Shin Chan": "Electronics",
    "Wire Protector - Shin Chan Bottom": "Electronics",
    "Wire Protector - Snorlax": "Electronics",
    "Wire Protector - Spiderman Head": "Electronics",
    "Wire Protector - Spiderman Round Face": "Electronics",
    "Wire Protector - Spongebob": "Electronics",
    "Wire Protector - Sprite": "Electronics",
    "Wire Protector - Squirtle": "Electronics",
    "Wire Protector - Starbucks Brown": "Electronics",
    "Wire Protector - Starbucks White": "Electronics",
    "Wire Protector - Stella Lou": "Electronics",
    "Wire Protector - Stitch": "Electronics",
    "Wire Protector - Sulley": "Electronics",
    "Wire Protector - Superman Logo": "Electronics",
    "Wire Protector - Tiger": "Electronics",
    "Wire Protector - Togepi": "Electronics",
    "Wire Protector - Totoro": "Electronics",
    "Wire Protector Bite - Psyduck": "Electronics",
    "Wire Protector Flight - Batman": "Electronics",
    "Wire Protector Flight - Captain America": "Electronics",
    "Wire Protector Flight - Green Lantern": "Electronics",
    "Wire Protector Flight - Hulk": "Electronics",
    "Wire Protector Flight - Ironman": "Electronics",
    "Wire Protector Flight - Spiderman": "Electronics",
    "Wire Protector Flight - Superman": "Electronics",
    "Wire Protector Flight - Venom": "Electronics",

    # =========================================================================
    # Wallets & Cases
    # =========================================================================
    "Airpod Case - Headset Lock Style - Black - Pro 2nd Gen": "Wallets & Cases",
    "Airpod Case - Headset Lock Style - Black - Regular 3rd Gen": "Wallets & Cases",
    "Airpod Case - Headset Lock Style - Black/Orange - Pro 2nd Gen": "Wallets & Cases",
    "Airpod Case - Headset Lock Style - Black/Orange - Regular 3rd Gen": "Wallets & Cases",
    "Airpod Case - Headset Lock Style - Black/Red - Pro 2nd Gen": "Wallets & Cases",
    "Airpod Case - Headset Lock Style - Black/Red - Pro 3rd Gen": "Wallets & Cases",
    "Airpod Case - Headset Lock Style - Black/Red - Regular 3rd Gen": "Wallets & Cases",
    "Airpod Case - Headset Lock Style - Black/White - Pro 2nd Gen": "Wallets & Cases",
    "Airpod Case - Headset Lock Style - Black/White - Regular 3rd Gen": "Wallets & Cases",
    "Airpod Case - Headset Lock Style - Navy - Pro 2nd Gen": "Wallets & Cases",
    "Airpod Case - Headset Lock Style - Navy - Regular 3rd Gen": "Wallets & Cases",
    "Airpod Case - Side Lock Style - Black - Pro 2nd Gen": "Wallets & Cases",
    "Airpod Case - Side Lock Style - Black - Regular 3rd Gen": "Wallets & Cases",
    "Airpod Case - Side Lock Style - Black - Regular 4th Gen": "Wallets & Cases",
    "Airpod Case - Side Lock Style - Green - Pro 2nd Gen": "Wallets & Cases",
    "Airpod Case - Side Lock Style - Green - Regular 3rd Gen": "Wallets & Cases",
    "Airpod Case - Side Lock Style - Green - Regular 4th Gen": "Wallets & Cases",
    "Airpod Case - Side Lock Style - Red - Pro 2nd Gen": "Wallets & Cases",
    "Airpod Case - Side Lock Style - Red - Regular 3rd Gen": "Wallets & Cases",
    "Airpod Case - Side Lock Style - Red - Regular 4th Gen": "Wallets & Cases",
    "Airpod Case - Side Lock Style - White - Pro 2nd Gen": "Wallets & Cases",
    "Airpod Case - Side Lock Style - White - Regular 3rd Gen": "Wallets & Cases",
    "Airpod Case - Side Lock Style - White - Regular 4th Gen": "Wallets & Cases",
    "Alligator Skin Textured Magsafe Wallet with Stand - Black": "Wallets & Cases",
    "Alligator Skin Textured Magsafe Wallet with Stand - Blue": "Wallets & Cases",
    "Alligator Skin Textured Magsafe Wallet with Stand - Brown": "Wallets & Cases",
    "Alligator Skin Textured Magsafe Wallet with Stand - Green": "Wallets & Cases",
    "Alligator Skin Textured Magsafe Wallet with Stand - Red": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Large Blue": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Large Green": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Large Green Shiny": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Large Orange": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Large Pink": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Large Pink Shiny": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Small Blue": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Small Blue Shiny": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Small Green": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Small Green Shiny": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Small Orange": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Small Pink": "Wallets & Cases",
    "Auto-close PU Leather Pouch - Small Pink Shiny": "Wallets & Cases",
    "Auto-close Silicone Pouch - Smal Green": "Wallets & Cases",
    "Auto-close Silicone Pouch - Small Black": "Wallets & Cases",
    "Auto-close Silicone Pouch - Small Cream": "Wallets & Cases",
    "Auto-close Silicone Pouch - Small Green": "Wallets & Cases",
    "Auto-close Silicone Pouch - Small Red": "Wallets & Cases",
    "Auto-close Silicone Pouch - Small White": "Wallets & Cases",
    "Card Ejector with Leather Wallet - Black": "Wallets & Cases",
    "Card Ejector with Leather Wallet - Black Carbon Fiber": "Wallets & Cases",
    "Card Ejector with Leather Wallet - Black Carbon Fiber with Buckle": "Wallets & Cases",
    "Card Ejector with Leather Wallet - Brown": "Wallets & Cases",
    "Card Ejector with Leather Wallet - Dark Brown": "Wallets & Cases",
    "Card Ejector with Leather Wallet - Navy Carbon Fiber with Buckle": "Wallets & Cases",
    "Card Ejector with Leather Wallet - Red": "Wallets & Cases",
    "Card Ejector with Leather Wallet - Red Carbon Fiber with Buckle": "Wallets & Cases",
    "Magsafe Wallet - Black": "Wallets & Cases",
    "Magsafe Wallet - Blue": "Wallets & Cases",
    "Magsafe Wallet - Brown": "Wallets & Cases",
    "Magsafe Wallet - Green": "Wallets & Cases",
    "Magsafe Wallet - Red": "Wallets & Cases",
    "Magsafe Wallet - Violet": "Wallets & Cases",
    "Magsafe Wallet - With Logo - Black": "Wallets & Cases",
    "Magsafe Wallet - With Logo - Brown": "Wallets & Cases",
    "Magsafe Wallet - With Logo - Violet": "Wallets & Cases",
    "Magsafe Wallet - Yellow": "Wallets & Cases",
    "Money Clip Steel - Black Dollar Sign": "Wallets & Cases",
    "Money Clip Steel - Gold": "Wallets & Cases",
    "Money Clip Steel - Silver": "Wallets & Cases",
    "Money Clip Steel - Silver Dollar Sign": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Black": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Black 9.5": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Brown": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Brown 9.5": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Dark Blue": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Dark Blue 9.5": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Dark Green 9.5": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Green": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Green 9.5": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Light Brown": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Light Brown 9.5": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Navy": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Navy 9.5": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Purple": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Purple 9.5": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Red": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Red 9.5": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Yellow": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand - Yellow 9.5": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand Design 2 - Black": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand Design 2 - Brown": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand Design 2 - Green": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand Design 2 - Navy": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand Design 2 - Purple": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand Design 2 - Red": "Wallets & Cases",
    "Plain Leather Magsafe Snap On Wallet with Stand Design 2 - Yellow": "Wallets & Cases",
    "RFID Card Wallet - Black": "Wallets & Cases",
    "RFID Card Wallet - Blue": "Wallets & Cases",
    "RFID Card Wallet - Gray": "Wallets & Cases",
    "RFID Card Wallet - Red": "Wallets & Cases",
    "RFID Card Wallet - Rose Gold": "Wallets & Cases",
    "RFID Card Wallet - Silver": "Wallets & Cases",
    "RFID Card Wallet with Money Clip - Honeycomb Black": "Wallets & Cases",
    "RFID Card Wallet with Money Clip - Honeycomb Black V2": "Wallets & Cases",
    "RFID Card Wallet with Money Clip - Plain Black": "Wallets & Cases",
    "RFID Card Wallet with Money Clip - Plain Blue": "Wallets & Cases",
    "RFID Card Wallet with Money Clip - Plain Gold": "Wallets & Cases",
    "RFID Card Wallet with Money Clip - Plain Gray": "Wallets & Cases",
    "RFID Card Wallet with Money Clip - Plain Green": "Wallets & Cases",
    "RFID Card Wallet with Money Clip - Plain Purple": "Wallets & Cases",
    "RFID Card Wallet with Money Clip - Plain Red": "Wallets & Cases",
    "RFID Card Wallet with Money Clip - Plain Silver": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 1st and 2nd Gen - Cliplock Style - Black": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 1st and 2nd Gen - Marshall": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 1st and 2nd Gen - Xbox Controller": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Carbon Fiber Texture - Black": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Carbon Fiber Texture - Red": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Carbon Fiber Texture - White": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Carbon Fiber Texture - Yellow": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Cliplock Style - Black": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Cliplock Style - Blue": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Cliplock Style - Red": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Controller - Black": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Controller - Gray": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Controller - White": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Famicom": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Green Dinosaur": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Marshall": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Minnie": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Nintendo Game Console": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - PS Controller": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Pokeball": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Switch": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 3rd Gen - Xbox Controller": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 4th Gen - Cliplock Style - Black": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 4th Gen - Controller - Ash Gray": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 4th Gen - Controller - Black": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 4th Gen - Controller - Gray": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - 4th Gen - Controller - White": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 1st Gen - Green Dinosaur": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 1st Gen - Hooded Spongebob": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 1st Gen - Instagram": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 1st Gen - Lucky Cat": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 1st Gen - Mike Wazowski": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 1st Gen - Minnie": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 1st Gen - PS Controller": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 1st Gen - Pooh": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 1st Gen - Sailormoon": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 1st Gen - Switch": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 1st Gen - Xbox Controller": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 1st Gen- Snorlax": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Carbon Fiber Texture - Black": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Carbon Fiber Texture - Red": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Carbon Fiber Texture - White": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Carbon Fiber Texture - Yellow": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Cliplock Style - Black": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Cliplock Style - Blue": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Cliplock Style - Red": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Controller - Black": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Controller - Gray": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Controller - White": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Famicom": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Marshall": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Nintendo Game Console": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - PS Controller": "Wallets & Cases",
    "Silicone Case Bluetooth Earphones - Pro 2nd Gen - Pokeball": "Wallets & Cases",
    "Small Multi-purpose Pouch - Blue": "Wallets & Cases",
    "Small Multi-purpose Pouch - Gray": "Wallets & Cases",
    "Small Multi-purpose Pouch - Red": "Wallets & Cases",
    "Small Multi-purpose Pouch - Yellow": "Wallets & Cases",
    "Spigen Airpod Case - Black - Pro 2nd Gen": "Wallets & Cases",
    "Spigen Airpod Case - Black - Regular 3rd Gen": "Wallets & Cases",
    "Spigen Airpod Case - White - Pro 2nd Gen": "Wallets & Cases",
    "Spigen Airpod Case - White - Regular 3rd Gen": "Wallets & Cases",

    # =========================================================================
    # Home & Living
    # =========================================================================
    "Arrow Hook - Black": "Home & Living",
    "Bird Shaped Self Watering Bulb for Plants - Blue": "Home & Living",
    "Bird Shaped Self Watering Bulb for Plants - Green": "Home & Living",
    "Bird Shaped Self Watering Bulb for Plants - Pink Tulip": "Home & Living",
    "Bird Shaped Self Watering Bulb for Plants - Red": "Home & Living",
    "Car Seat Headrest Hook - Double Hook Black": "Home & Living",
    "Car Seat Headrest Hook - Double Hook Brown": "Home & Living",
    "Car Seat Headrest Hook - Double Hook Gray": "Home & Living",
    "Chipmunk Hook - Gray": "Home & Living",
    "Chipmunk Hook - Pink": "Home & Living",
    "Cockroach Killing Powder - 50g pack": "Home & Living",
    "Cup Cover - Bell - Light Blue": "Home & Living",
    "Cup Cover - Bell - Orange": "Home & Living",
    "Cup Cover - Bell - Yellow": "Home & Living",
    "Cup Cover - Cat Ears - Orange / Black": "Home & Living",
    "Cup Cover - Cat Ears - Pink / White": "Home & Living",
    "Cup Cover - Cat Ears - Sky Blue / Pink": "Home & Living",
    "Diatomite Coaster - Cute Animal Design  - Cat - Large": "Home & Living",
    "Diatomite Coaster - Cute Animal Design  - Fox": "Home & Living",
    "Diatomite Coaster - Cute Animal Design  - Husky": "Home & Living",
    "Diatomite Coaster - Cute Animal Design  - Owl": "Home & Living",
    "Diatomite Coaster - Cute Animal Design  - Panda": "Home & Living",
    "Diatomite Coaster - Cute Animal Design  - Pig": "Home & Living",
    "Diatomite Coaster - Cute Animal Design  - Polar Bear": "Home & Living",
    "Diatomite Coaster - Cute Animal Design  - Shiba Inu": "Home & Living",
    "Diatomite Coaster - Cute Animal Design  - White Bear - Large": "Home & Living",
    "Diatomite Coaster - Cute Animal Design  - Winking Cat": "Home & Living",
    "Diatomite Coaster Design 1 - Hard - Round Dark Gray": "Home & Living",
    "Diatomite Coaster Design 1 - Hard - Round Gray": "Home & Living",
    "Diatomite Coaster Design 1 - Hard - Round Light Blue": "Home & Living",
    "Diatomite Coaster Design 1 - Hard - Round Light Green": "Home & Living",
    "Diatomite Coaster Design 1 - Hard - Round Pink": "Home & Living",
    "Diatomite Coaster Design 1 - Hard - Round White": "Home & Living",
    "Diatomite Coaster Design 1 - Hard - Square Dark Gray": "Home & Living",
    "Diatomite Coaster Design 1 - Hard - Square Gray": "Home & Living",
    "Diatomite Coaster Design 1 - Hard - Square Light Blue": "Home & Living",
    "Diatomite Coaster Design 1 - Hard - Square Light Green": "Home & Living",
    "Diatomite Coaster Design 1 - Hard - Square Pink": "Home & Living",
    "Diatomite Coaster Design 1 - Hard - Square White": "Home & Living",
    "Diatomite Coaster Design 2 - Flexible Rubber Bottom - Black": "Home & Living",
    "Diatomite Coaster Design 2 - Flexible Rubber Bottom - White": "Home & Living",
    "Elephant Hook - Green": "Home & Living",
    "Elephant Hook - Pink": "Home & Living",
    "Elephant Hook - Yellow": "Home & Living",
    "Extendable Bookend - Black": "Home & Living",
    "Foldable Silicone Tumbler - Gray": "Home & Living",
    "Foldable Silicone Tumbler - Light Green": "Home & Living",
    "Foldable Silicone Tumbler - Pink": "Home & Living",
    "Foldable Silicone Tumbler - Sky Blue": "Home & Living",
    "Food Sealing Clamp Design 1 - Large - Blue": "Home & Living",
    "Food Sealing Clamp Design 1 - Large - Pink": "Home & Living",
    "Food Sealing Clamp Design 1 - Large - White": "Home & Living",
    "Food Sealing Clamp Design 2 - Small - Blue": "Home & Living",
    "Food Sealing Clamp Design 2 - Small - Green": "Home & Living",
    "Food Sealing Clamp Design 2 - Small - Pink": "Home & Living",
    "Food Sealing Clamp Design 2 - Small - Yellow": "Home & Living",
    "Gardening Grow Bag - Beige - 10 Gallon (40*30cm)": "Home & Living",
    "Gardening Grow Bag - Beige - 2 Gallon (20*20cm)": "Home & Living",
    "Gardening Grow Bag - Beige - 3 Gallon (25*22cm)": "Home & Living",
    "Gardening Grow Bag - Beige - 5 Gallon (30*25cm)": "Home & Living",
    "Gardening Grow Bag - Gray - 10 Gallon (40*30cm)": "Home & Living",
    "Gardening Grow Bag - Gray - 2 Gallon (20*20cm)": "Home & Living",
    "Gardening Grow Bag - Gray - 3 Gallon (25*22cm)": "Home & Living",
    "Gardening Grow Bag - Gray - 5 Gallon (30*25cm)": "Home & Living",
    "Gardening Grow Bag - Light Brown - 2 Gallon (20*20cm)": "Home & Living",
    "Gardening Grow Bag - Light Brown - 3 Gallon (25*22cm)": "Home & Living",
    "Gardening Grow Bag - Light Brown - 5 Gallon (30*25cm)": "Home & Living",
    "Gardening Grow Bag - Nude Brown - 10 Gallon (40*30)": "Home & Living",
    "Gardening Grow Bag Design 2 - Black - 1 Gallon (18*15cm) no handle": "Home & Living",
    "Gardening Grow Bag Design 2 - Black - 10 Gallon (40*30cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Black - 2 Gallon (20*20cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Black - 20 Gallon (50*40cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Black - 3 Gallon (25*22cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Black - 5 Gallon (30*25cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Black - 7 Gallon (35*30cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Gray - 10 Gallon (40*30cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Gray - 2 Gallon (20*20cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Gray - 20 Gallon (50*40cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Gray - 3 Gallon (25*22cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Gray - 5 Gallon (30*25cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Gray - 7 Gallon (35*30cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Green - 10 Gallon (40*30cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Green - 2 Gallon (20*20cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Green - 2 Gallon (20*20cm) NO HANDLE": "Home & Living",
    "Gardening Grow Bag Design 2 - Green - 20 Gallon (50*40cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Green - 3 Gallon (25*22cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Green - 5 Gallon (30*25cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Green - 7 Gallon (35*30cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Light Brown - 10 Gallon (40*30cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Light Brown - 2 Gallon (20*20cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Light Brown - 20 Gallon (50*40cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Light Brown - 3 Gallon (25*22cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Light Brown - 5 Gallon (30*25cm)": "Home & Living",
    "Gardening Grow Bag Design 2 - Light Brown - 7 Gallon (35*30cm)": "Home & Living",
    "Gardening Grow Bag Design 3 - White - 10 Gallon (40*30cm)": "Home & Living",
    "Gardening Grow Bag Design 3 - White - 20 Gallon (50*40cm)": "Home & Living",
    "Gardening Grow Bag Design 3 - White - 5 Gallon (30*25cm)": "Home & Living",
    "Gardening Grow Bag Design 3 - White - 7 Gallon (35*30cm)": "Home & Living",
    "Hat Hook - Black": "Home & Living",
    "Hat Hook - White": "Home & Living",
    "Metal Bookend - Black": "Home & Living",
    "Metal Bookend - Gray": "Home & Living",
    "Metal Bookend - White": "Home & Living",
    "Microfiber Cooling Towel (30*80cm)  - Blue": "Home & Living",
    "Microfiber Cooling Towel (30*80cm)  - Dark Gray": "Home & Living",
    "Microfiber Cooling Towel (30*80cm)  - Fuschia": "Home & Living",
    "Microfiber Cooling Towel (30*80cm)  - Gray": "Home & Living",
    "Microfiber Cooling Towel (30*80cm)  - Green": "Home & Living",
    "Microfiber Cooling Towel (30*80cm)  - Orange": "Home & Living",
    "Microfiber Cooling Towel (30*80cm)  - Pink": "Home & Living",
    "Microfiber Cooling Towel (30*80cm)  - Red": "Home & Living",
    "Microfiber Cooling Towel (30*80cm)  - Violet": "Home & Living",
    "Retro Vinyl Coaster - Set of 2": "Home & Living",
    "Retro Vinyl Coaster - Set of 6": "Home & Living",
    "Silicone Coaster Design Drain - Black": "Home & Living",
    "Silicone Coaster Design Drain - Blue": "Home & Living",
    "Silicone Coaster Design Drain - Cream": "Home & Living",
    "Silicone Coaster Design Drain - Gray": "Home & Living",
    "Silicone Coaster Design Drain - Pink": "Home & Living",
    "Silicone Coaster Design Drain - Random": "Home & Living",
    "Silicone Coaster Design Drain - Yellow": "Home & Living",
    "Wooden Bookend - Dark Walnut Large Round No Logo": "Home & Living",
    "Wooden Bookend - Dark Walnut Large Square No Logo": "Home & Living",
    "Wooden Bookend - Dark Walnut Small Round No Logo": "Home & Living",
    "Wooden Bookend - Dark Walnut Small Square No Logo": "Home & Living",
    "Wooden Bookend - Nature Round Corner": "Home & Living",
    "Wooden Bookend - Nature Square Corner": "Home & Living",
    "Wooden Bookend - No Print Round Corner": "Home & Living",
    "Wooden Bookend - No Print Square Corner": "Home & Living",
    "Wooden Coaster Design 1 - Round": "Home & Living",

    # =========================================================================
    # Toys
    # =========================================================================
    "Fidget Toy - Brick Black": "Toys",
    "Fidget Toy - Brick White": "Toys",
    "Fidget Toy - Buttons Black": "Toys",
    "Fidget Toy - Buttons White": "Toys",
    "Fidget Toy - Metal Card - Ace": "Toys",
    "Fidget Toy - Metal Card - Brass King / Copper Witch": "Toys",
    "Fidget Toy - Metal Card - Joker": "Toys",
    "Fidget Toy - Metal Card - King": "Toys",
    "Fidget Toy - Metal Card - Silver King": "Toys",
    "Fidget Toy - Stripes Black": "Toys",
    "Fidget Toy - Stripes White": "Toys",
    "Lego DIY Calendar - Blue - Police": "Toys",
    "Lego DIY Calendar - Green - Soldier": "Toys",
    "Lego DIY Calendar - Orange - Engineer": "Toys",
    "Lego DIY Calendar - White - Racer": "Toys",
    "Sembo Block Set 3D Puzzle - City Street - Arcade Shop": "Toys",
    "Sembo Block Set 3D Puzzle - City Street - Beverage Store": "Toys",
    "Sembo Block Set 3D Puzzle - City Street - CC Ornament Store": "Toys",
    "Sembo Block Set 3D Puzzle - City Street - Candy Store": "Toys",
    "Sembo Block Set 3D Puzzle - City Street - Coffee Shop": "Toys",
    "Sembo Block Set 3D Puzzle - City Street - Musical Instrument Shop": "Toys",
    "Sembo Block Set 3D Puzzle - City Street - Popcorn Shop": "Toys",
    "Sembo Block Set 3D Puzzle - City Street - Tea House": "Toys",

    # =========================================================================
    # Stationery
    # =========================================================================
    "Gel Pen": "Stationery",
    "Portable Double Sided Desk Mat - Black/Red": "Stationery",
    "Portable Double Sided Desk Mat - Blue/Yellow": "Stationery",
    "Portable Double Sided Desk Mat - Gray/Blue": "Stationery",
    "Portable Double Sided Desk Mat - Gray/Green": "Stationery",
    "Portable Double Sided Desk Mat - Gray/Orange": "Stationery",
    "Portable Double Sided Desk Mat - Gray/Pink": "Stationery",
    "Portable Double Sided Desk Mat - Mint/Pink": "Stationery",
    "Portable Double Sided Desk Mat - Mint/Sky Blue": "Stationery",
    "Portable Double Sided Desk Mat - Pink/Sky Blue": "Stationery",
    "Portable Double Sided Desk Mat - Red/Yellow": "Stationery",
    "Retractable Highlighter - Macaroon Colors - Set of 6": "Stationery",
    "Retractable Highlighter - Neon Colors - Set of 3": "Stationery",
    "Retractable Highlighter - Neon Colors - Set of 3A": "Stationery",
    "Retractable Highlighter - Neon Colors - Set of 6": "Stationery",
    "Retractable Highlighter - Pen - Neon Green": "Stationery",
    "Retractable Highlighter - Pen - Neon Orange": "Stationery",
    "Retractable Highlighter - Pen - Neon Pink": "Stationery",
    "Retractable Highlighter - Pen - Neon Yellow": "Stationery",
    "Retractable Highlighter - Refill - Neon Green": "Stationery",
    "Retractable Highlighter - Refill - Neon Orange": "Stationery",
    "Retractable Highlighter - Refill - Neon Pink": "Stationery",
    "Retractable Highlighter - Refill - Neon Purple": "Stationery",
    "Retractable Highlighter - Refill - Neon Yellow": "Stationery",
    "Retractable Highlighter - Refill - Soft Blue": "Stationery",
    "Retractable Highlighter - Soft Colors - Set of 6": "Stationery",
    "Retractable Highlighter - Top Picks - Set of 3A": "Stationery",
    "Retractable Highlighter - Top Picks - Set of 3B": "Stationery",
    "Sticky Notes Freebie - Assorted": "Stationery",
}

df = pd.read_csv('../data/processed/Processed_Data.csv')

df['Item Description'] = df['Item Description'].str.strip()

df['Category'] = df['Item Description'].map(product_categories)

missing = df[df['Category'].isna()]['Item Description'].unique()
if len(missing) > 0:
    print(f"Warning: {len(missing)} items were not in your dictionary.")

df.to_csv('../data/processed/Categorized_Data.csv', index=False)
